[tool.poetry]
name = "checkers-robot-s24982"
description = ""
authors = ["OlekZima <zimenkoalex34@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pandas = "^2.2.3"
numpy = "^2.1.3"
pydobotplus = "^0.1.2"
customtkinter = "^5.2.2"
opencv-python = "^4.10.0.84"
pillow = "^11.0.0"
pysimplegui = "^5.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
