name: Apply formatting

on: push

permissions:
  contents: write

jobs:
  format:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Apply formatting"
          git push
